### ISSUE TITLE
User login sessions

### ISSUE THREAD

**Issue by fippli** [skewlab/go-back#12]

**Comment by dskeppstedt** [comment]
Hur är det tänk att det ska fungera?
Jag byggde ett system för mitt projekt [lista](https://github.com/dskeppstedt/lista-api/tree/d299d753bbd4189c976d45da7c949679e40390dd) som bygger på JWT och ett refresh token som kanske kan vara av intresse?

**Comment by jjojo** [comment]
JWT och refresh token låter som en bra och modern lösning! Definitivt av intresse. Vi har inte tänkt igenom det supermycket men så länge det är säkert och gör så man inte behöver logga in varje gång så är vi nöjda. Men ja JWT har alltid varit tanken från min sida iaf

**Comment by fippli** [comment]
Hur skulle du känna för att implementera sessions i det här projektet David?
I så fall är det bara checka ut en branch och skapa typ en sessions modul i en egen mapp
kanske under
/api/sessions eller typ /modules/sessions eller nåt liknande

**Comment by dskeppstedt** [comment]
Yes, ska göra ett försök!

**Comment by dskeppstedt** [comment]
@fippli @jjojo Har kollat lite på projektet nu. Som jag förstår det så använder vi echo som ramverk?
isåfall kommer jag basera lösningen på det!

**Comment by fippli** [comment]
Japp det stämmer. Det låter bra. Om det går att använda echo så är det ju bra!

**Comment by fippli** [comment]
Hittade det här:
https://echo.labstack.com/middleware/jwt

**Comment by dskeppstedt** [comment]
Exakt det jag tänkte köra på, har bara inte haft tid ännu.
